FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src
COPY database/scripts /app/scripts

ENV PYTHONPATH=/app/src
ENV DATA_DIR=/data

CMD ["python", "/app/scripts/load_data.py"]
